name: 'Deploy Infrastructure and Function App'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '**.tf'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'GetResumeVisitorCounter'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/api'
  PYTHON_VERSION: '3.11'
  ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.CRC_AZURE_CREDS).subscriptionId }}
  ARM_CLIENT_ID: ${{ fromJson(secrets.CRC_AZURE_CREDS).clientId }}
  ARM_CLIENT_SECRET: ${{ fromJson(secrets.CRC_AZURE_CREDS).clientSecret }}
  ARM_TENANT_ID: ${{ fromJson(secrets.CRC_AZURE_CREDS).tenantId }}

jobs:
  infrastructure-check:
    name: 'Check Infrastructure'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CRC_AZURE_CREDS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.10.3'

    - name: Terraform Init
      id: init
      run: |
        cd backend/terraform
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        cd backend/terraform
        terraform plan \
          -detailed-exitcode \
          -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" \
          -out=tfplan
        echo "PLAN_EXIT_CODE=$?" >> $GITHUB_ENV
      continue-on-error: true
    

    - name: Terraform Apply
      if: ${{ env.PLAN_EXIT_CODE == '2' }}
      run: terraform apply tfplan

  deploy-function:
    name: 'Deploy Function App'
    needs: infrastructure-check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true