name: deploy_backend
# GitHub Actions workflow to deploy the backend of the Cloud Resume Challenge to Azure Blob Storage

on:
    push:
        branches: [ main ]
        paths:
            - 'backend/**'  # Trigger only if changes occur in the backend folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.CRC_AZURE_CREDS }}

    # Step 3: Upload backend files to Azure Blob Storage
    - name: Upload to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch \
              --account-name cloudresumechallengedp \
              --auth-mode key \
              --destination '$web' \
              --source ./backend  # Upload from backend folder

    # Step 4: Purge CDN to refresh backend content (Optional)
    - name: Purge CDN Endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge \
             --content-paths "/*" \
             --profile-name "cloudresumechallengedp" \
             --name "cloudresumechallendedp-dgh5hahkb9cmh8h3.z03.azurefd.net" \
             --resource-group cloudresumechallenge-dineshpalli

    # Step 5: Azure Logout (Best practice)
    - name: Logout
      run: |
            az logout
      if: always()
