name: deploy_backend_function_app
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/api/**'  # Only trigger when changes are made in backend/api folder
  workflow_dispatch:  # Allows manual triggering

env:
  AZURE_FUNCTIONAPP_NAME: 'GetResumeVisitorCounter'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/api'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CRC_AZURE_CREDS }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true
        scm-do-build-during-deployment: true
        enable-oryx-build: true