name: deploy_frontend
# GitHub Actions workflow to deploy the frontend of the Cloud Resume Challenge to Azure Blob Storage

on:
    push:
        branches: [ main ]
        paths:
            - 'frontend/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.CRC_AZURE_CREDS }}

    - name: Debug directory
      run: |
        pwd
        ls -la

    - name: Upload to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            # Upload the contents of the frontend folder to the $web container
            az storage blob upload-batch \
              --account-name cloudresumechallengedp \
              --auth-mode key \
              --destination '$web' \
              --source ./frontend \

    - name: Purge CDN Endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge \
             --content-paths "/*" \
             --profile-name "cloudresumechallengedp" \
             --name "cloudresumechallengedp-endpoint" \
             --resource-group cloudresumechallenge-dineshpalli

    - name: Logout
      run: |
            az logout
      if: always()